source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.2'

group :development, :test do
	gem 'pry-nav'
  gem 'rspec'
  gem 'rubocop-rails', require: false
end

gemspec
