require 'bundler/setup'
Bundler.require(:development)

require 'rom/sql/rake_task'
require_relative 'lib/url-shortener'

namespace :db do
  task :setup do
    connection_uri = UrlShortener::DataMapper::DatabaseConnection.connection_uri(UrlShortener::DataMapper::DatabaseConnection.connection_options)

    config = ROM::Configuration.new(:sql, connection_uri, {})
    ROM::SQL::RakeSupport.env = ROM.container(config)
  end
end
